language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "Settlers-Of-FSA-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: settlers-of-fsa # see README
  api_key:
    secure: 'ik/t0sEA4vXaX78DDCzI8bxt12Rw+AquVkXb2geqMPL1nbsLp3QIiDWyy5eC5U40l/FWFXxW+cBguPWm9mfkhQi1cMpt24cf+Ug4QEoy1FNatYdEjD4Zq2STMhJL5ZcXGABNFiBwxJiPYY5BCiTXi7RDg7uYDyMXiErBZTMcWJEiOorBnBIyO+689gD1rfnMVG3rLqv2IbK//XQRKt0A99/3YjQcvqVPedAiIqUjCSjUMvyRElW5p5LVVPtZaLny2KUXH2ayEggfmcyqneSMwzFzCOK8g30E0lr42dZ7n+oJ+EslRt2tGe3hr3n5hlPVC+QIXlB+DXSuC3zBXDktGRDaIyIXOykNokZhiCy66gezpfpg2EG2NHXe0Ba/+6SGx8eCu6OekLUv9GfqOU6ha3clyCrf7O+BecjNN7MIFnbTKkIu2EvxxfSumH+gDZ7B+f4nbgu4RmsA2pzenAe7i2AGUMC83PPK3lS+9+vlALpix5TGCWnOOmAaBUCUOmyZEHVSsJ9ObyhNxffM5Nl+E75FHfg3UKeKXo3KaSw8o/Prkb1fCeVLLi/GKgZgahVD39uQYLSK4CyqQayU+B8HDFbb2PyLtz7FK730JZGpARlR2IfRT2Q4SIlEWhKFs4suo8+JHHdPRtYUFGOl4PLTDA+EUxASvNgNlDC87Yv1Du0=' # see README
